/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER p7 IDENTIFIED BY "p7"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER p7 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO p7;
GRANT "RESOURCE" TO p7;
ALTER USER p7 DEFAULT ROLE "RESOURCE";

/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER p7 IDENTIFIED BY "MDY3131.practica_7"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER p7 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO p7;
GRANT "RESOURCE" TO p7;
ALTER USER p7 DEFAULT ROLE "RESOURCE"