drop table errores;
drop table detalle;
drop table descuentoentradas;
drop table ticket;
drop table totalgeneralcine;
drop table resumen_cine;
drop table resumen_peliculas;
drop table venta;
drop table sala;
drop table usuario;
drop table region;
drop table cine;
drop table tiposala;
drop table peliculas;
drop table calificaciones;
drop table categoria;

CREATE TABLE calificaciones (
    idcalificacion   NUMBER NOT NULL,
    descripcion      VARCHAR2(45 BYTE) NOT NULL
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE UNIQUE INDEX calificaciones_pk ON
    calificaciones ( idcalificacion ASC )
        TABLESPACE system PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE calificaciones ADD CONSTRAINT calificaciones_pk PRIMARY KEY ( idcalificacion )
    USING INDEX calificaciones_pk;

CREATE TABLE categoria (
    idcategoria   NUMBER NOT NULL,
    descripcion   VARCHAR2(45 BYTE) NOT NULL
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE UNIQUE INDEX categoria_pk ON
    categoria ( idcategoria ASC )
        TABLESPACE system PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE categoria ADD CONSTRAINT categoria_pk PRIMARY KEY ( idcategoria )
    USING INDEX categoria_pk;

CREATE TABLE cine (
    idcine        NUMBER NOT NULL,
    nombre        VARCHAR2(45 BYTE),
    numerosalas   NUMBER NOT NULL,
    comuna        VARCHAR2(45 BYTE) NOT NULL,
    direccion     VARCHAR2(45 BYTE) NOT NULL
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE UNIQUE INDEX cine_pk ON
    cine ( idcine ASC )
        TABLESPACE system PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE cine ADD CONSTRAINT cine_pk PRIMARY KEY ( idcine )
    USING INDEX cine_pk;

CREATE TABLE descuentoentradas (
    iddesc             NUMBER NOT NULL,
    porcentaje         NUMBER(3,2) NOT NULL,
    valorentrada_min   NUMBER NOT NULL,
    valorentrada_max   NUMBER NOT NULL
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE TABLE detalle (
    idticket   NUMBER NOT NULL,
    idventa    NUMBER NOT NULL,
    adulto     CHAR(1 BYTE)
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE UNIQUE INDEX detalle_pk ON
    detalle (
        idticket
    ASC,
        idventa
    ASC )
        TABLESPACE system PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE detalle ADD CONSTRAINT detalle_pk PRIMARY KEY ( idticket,idventa )
    USING INDEX detalle_pk;

CREATE TABLE errores (
    correlativo   NUMBER NOT NULL,
    codigo        NUMBER,
    descripcion   VARCHAR2(50 BYTE),
    fecha         DATE
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE UNIQUE INDEX errores_pk ON
    errores ( correlativo ASC )
        TABLESPACE system PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE errores ADD CONSTRAINT errores_pk PRIMARY KEY ( correlativo )
    USING INDEX errores_pk;

CREATE TABLE peliculas (
    idpelicula       NUMBER NOT NULL,
    titulo           VARCHAR2(45 BYTE) NOT NULL,
    director         VARCHAR2(45 BYTE) NOT NULL,
    precio           NUMBER,
    estreno          CHAR(1 BYTE),
    idioma           VARCHAR2(45 BYTE),
    idcategoria      NUMBER NOT NULL,
    idcalificacion   NUMBER NOT NULL
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE UNIQUE INDEX peliculas_pk ON
    peliculas ( idpelicula ASC )
        TABLESPACE system PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE peliculas ADD CONSTRAINT peliculas_pk PRIMARY KEY ( idpelicula )
    USING INDEX peliculas_pk;

CREATE TABLE region (
    idregion      NUMBER NOT NULL,
    descripcion   VARCHAR2(45 BYTE) NOT NULL
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE UNIQUE INDEX region_pk ON
    region ( idregion ASC )
        TABLESPACE system PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE region ADD CONSTRAINT region_pk PRIMARY KEY ( idregion )
    USING INDEX region_pk;

CREATE TABLE sala (
    idsala           NUMBER NOT NULL,
    numeroasientos   NUMBER,
    climatizador     CHAR(1 BYTE),
    sonido4k         CHAR(1 BYTE),
    idtiposala       NUMBER NOT NULL
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE UNIQUE INDEX sala_pk ON
    sala ( idsala ASC )
        TABLESPACE system PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE sala ADD CONSTRAINT sala_pk PRIMARY KEY ( idsala )
    USING INDEX sala_pk;

CREATE TABLE ticket (
    idticket        NUMBER NOT NULL,
    numeroasiento   NUMBER NOT NULL,
    letra           VARCHAR2(1 BYTE) NOT NULL,
    descuento       NUMBER,
    cine_idcine     NUMBER NOT NULL,
    sala_idsala     NUMBER NOT NULL
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE UNIQUE INDEX ticket_pk ON
    ticket ( idticket ASC )
        TABLESPACE system PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE ticket ADD CONSTRAINT ticket_pk PRIMARY KEY ( idticket )
    USING INDEX ticket_pk;

CREATE TABLE tiposala (
    idtiposala    NUMBER NOT NULL,
    descripcion   VARCHAR2(45 BYTE) NOT NULL,
    cargoextra    CHAR(1 BYTE)
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE UNIQUE INDEX tiposala_pk ON
    tiposala ( idtiposala ASC )
        TABLESPACE system PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE tiposala ADD CONSTRAINT tiposala_pk PRIMARY KEY ( idtiposala )
    USING INDEX tiposala_pk;

CREATE TABLE totalgeneralcine (
    idcalculo          NUMBER NOT NULL,
    nombrecine         VARCHAR2(45 BYTE),
    fecha              DATE,
    peliculamasvista   VARCHAR2(45 BYTE),
    totalentradas      NUMBER
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE UNIQUE INDEX totalgeneralcine_pk ON
    totalgeneralcine ( idcalculo ASC )
        TABLESPACE system PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE totalgeneralcine ADD CONSTRAINT totalgeneralcine_pk PRIMARY KEY ( idcalculo )
    USING INDEX totalgeneralcine_pk;

CREATE TABLE usuario (
    idusuario   NUMBER NOT NULL,
    nombre      VARCHAR2(45 BYTE),
    apellido    VARCHAR2(45 BYTE),
    edad        NUMBER,
    idregion    NUMBER NOT NULL
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE UNIQUE INDEX usuario_pk ON
    usuario ( idusuario ASC )
        TABLESPACE system PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE usuario ADD CONSTRAINT usuario_pk PRIMARY KEY ( idusuario )
    USING INDEX usuario_pk;

CREATE TABLE venta (
    idventa      NUMBER NOT NULL,
    subtotal     NUMBER,
    descuento    NUMBER,
    total        NUMBER,
    fecha        DATE,
    idpelicula   NUMBER NOT NULL,
    idusuario    NUMBER NOT NULL
)
    PCTFREE 10 PCTUSED 40 TABLESPACE system LOGGING
        STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE UNIQUE INDEX venta_pk ON
    venta ( idventa ASC )
        TABLESPACE system PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE venta ADD CONSTRAINT venta_pk PRIMARY KEY ( idventa )
    USING INDEX venta_pk;

ALTER TABLE detalle ADD CONSTRAINT detalle_ticket_fk FOREIGN KEY ( idticket )
    REFERENCES ticket ( idticket )
NOT DEFERRABLE;

ALTER TABLE detalle ADD CONSTRAINT detalle_venta_fk FOREIGN KEY ( idventa )
    REFERENCES venta ( idventa )
NOT DEFERRABLE;

ALTER TABLE peliculas ADD CONSTRAINT peliculas_calificaciones_fk FOREIGN KEY ( idcalificacion )
    REFERENCES calificaciones ( idcalificacion )
NOT DEFERRABLE;

ALTER TABLE peliculas ADD CONSTRAINT peliculas_categoria_fk FOREIGN KEY ( idcategoria )
    REFERENCES categoria ( idcategoria )
NOT DEFERRABLE;

ALTER TABLE sala ADD CONSTRAINT sala_tiposala_fk FOREIGN KEY ( idtiposala )
    REFERENCES tiposala ( idtiposala )
NOT DEFERRABLE;

ALTER TABLE ticket ADD CONSTRAINT ticket_cine_fk FOREIGN KEY ( cine_idcine )
    REFERENCES cine ( idcine )
NOT DEFERRABLE;

ALTER TABLE ticket ADD CONSTRAINT ticket_sala_fk FOREIGN KEY ( sala_idsala )
    REFERENCES sala ( idsala )
NOT DEFERRABLE;

ALTER TABLE usuario ADD CONSTRAINT usuario_region_fk FOREIGN KEY ( idregion )
    REFERENCES region ( idregion )
NOT DEFERRABLE;

ALTER TABLE venta ADD CONSTRAINT venta_peliculas_fk FOREIGN KEY ( idpelicula )
    REFERENCES peliculas ( idpelicula )
NOT DEFERRABLE;

ALTER TABLE venta ADD CONSTRAINT venta_usuario_fk FOREIGN KEY ( idusuario )
    REFERENCES usuario ( idusuario )
NOT DEFERRABLE;

--------------------------------------------------------------------------------

--INSERTAR REGISTROS
INSERT INTO TIPOSALA VALUES(1,'IMAX','S');
INSERT INTO TIPOSALA VALUES(2,'4DX','S');
INSERT INTO TIPOSALA VALUES(3,'PALCO','S');
INSERT INTO TIPOSALA VALUES(4,'PREMIER','S');
INSERT INTO TIPOSALA VALUES(5,'REAL 3D','S');
INSERT INTO TIPOSALA VALUES(6,'NORMAL','N');

INSERT INTO REGION VALUES(1,'RM');
INSERT INTO REGION VALUES(2,'REGION V');
INSERT INTO REGION VALUES(3,'REGION VI');
INSERT INTO REGION VALUES(4,'REGION IIX');
INSERT INTO REGION VALUES(5,'REGION IX');
INSERT INTO REGION VALUES(6,'REGION XII');
INSERT INTO REGION VALUES(7,'REGION I');
INSERT INTO REGION VALUES(8,'REGION II');

INSERT INTO CALIFICACIONES VALUES(1,'TODO ESPECTADOR');
INSERT INTO CALIFICACIONES VALUES(2,'TODO ESPECTADOR MAYOR 7');
INSERT INTO CALIFICACIONES VALUES(3,'MAYORES DE 14');
INSERT INTO CALIFICACIONES VALUES(4,'MAYORES DE 18');

INSERT INTO SALA VALUES(1,100,'S','S',6);
INSERT INTO SALA VALUES(2,120,'S','S',2);
INSERT INTO SALA VALUES(3,120,'S','S',3);
INSERT INTO SALA VALUES(4,100,'S','S',3);
INSERT INTO SALA VALUES(5,140,'S','S',5);
INSERT INTO SALA VALUES(6,140,'S','S',1);
INSERT INTO SALA VALUES(7,100,'N','N',6);

INSERT INTO CINE VALUES(1,'CINE REX', 3,'MACUL','AV. LAS CARDENAS 4434');
INSERT INTO CINE VALUES(2,'CINE CAUPOLICAN', 7,'SANTIAGO CENTRO','HUERFANOS 665');
INSERT INTO CINE VALUES(3,'CINE LIDO', 5,'RECOLETA','AV. LAS TORRES 5444');
INSERT INTO CINE VALUES(4,'CINE REAL', 4,'SAN BERNARDO','AV. CORONEL 122');
INSERT INTO CINE VALUES(5,'CINE ASTOR', 3,'PROVIDENCIA','NUEVA PROVIDENCIA 2001');
INSERT INTO CINE VALUES(6,'GRAN CINERAMA', 2,'LA FLORIDA','COSTANERA 277');

INSERT INTO USUARIO VALUES(1,'OSCAR','MIRANDA',34, 1);
INSERT INTO USUARIO VALUES(2,'MARCELO','CASTRO',24, 1);
INSERT INTO USUARIO VALUES(3,'ALDO','CASTRO',36, 6);
INSERT INTO USUARIO VALUES(4,'MARTINA','LARA',19, 6);
INSERT INTO USUARIO VALUES(5,'CARMEN','SEGOVIA',30, 1);
INSERT INTO USUARIO VALUES(6,'RAUL','MENDIETA',28, 4);
INSERT INTO USUARIO VALUES(7,'DANIELA','CARMONA',29, 4);
INSERT INTO USUARIO VALUES(8,'MARCELO','FUENTES',35, 1);
INSERT INTO USUARIO VALUES(9,'RAMON','SEGOVIA',18, 1);
INSERT INTO USUARIO VALUES(10,'MARTIN','PEREZ',17, 2);
INSERT INTO USUARIO VALUES(11,'JAIME','PERALTA',23, 2);

INSERT INTO CATEGORIA VALUES(1,'CIENCIA FICCION');
INSERT INTO CATEGORIA VALUES(2,'TERROR');
INSERT INTO CATEGORIA VALUES(3,'SUSPENSO');
INSERT INTO CATEGORIA VALUES(4,'COMEDIA');
INSERT INTO CATEGORIA VALUES(5,'INFANTIL');
INSERT INTO CATEGORIA VALUES(6,'DRAMA');

INSERT INTO PELICULAS VALUES(1,'JUANITO HORMIGA','OSCAR POZO',2500,'S','ESPAÑOL',5,1);
INSERT INTO PELICULAS VALUES(2,'ORCAS','LUMI THON',5500,'S','INGLES',2,4);
INSERT INTO PELICULAS VALUES(3,'CHILE 2099','MIGEL LITON',4500,'N','ESPAÑOL',6,3);
INSERT INTO PELICULAS VALUES(4,'NOCHE SIN FIN','HERMANOS LOTO',3500,'S','INGLES',1,2);
INSERT INTO PELICULAS VALUES(5,'DANZA CON PERROS','MARK ROLACK',3500,'S','INGLES',5,1);
INSERT INTO PELICULAS VALUES(6,'TORIBIO','JIMMY LU',2500,'S','INGLES',4,3);
INSERT INTO PELICULAS VALUES(7,'HULKY','RAMON LARA',2500,'N','EXPAÑOL',4,4);
INSERT INTO PELICULAS VALUES(8,'DIAS Y NOCHES','FAN-YO LIN',5500,'S','INGLES',2,4);
INSERT INTO PELICULAS VALUES(9,'CHISPAS','MANU LOPEZ',3500,'N','ESPAÑOL',3,3);

INSERT INTO VENTA VALUES(1,0,0,0,TO_DATE('10-12-2016','dd-mm-yyyy'),1,1);
INSERT INTO VENTA VALUES(2,0,0,0,TO_DATE('05-03-2016','dd-mm-yyyy'),2,2);
INSERT INTO VENTA VALUES(3,0,0,0,TO_DATE('04-12-2016','dd-mm-yyyy'),1,3);
INSERT INTO VENTA VALUES(4,0,0,0,TO_DATE('06-11-2016','dd-mm-yyyy'),7,3);
INSERT INTO VENTA VALUES(5,0,0,0,TO_DATE('10-12-2016','dd-mm-yyyy'),6,3);
INSERT INTO VENTA VALUES(6,0,0,0,TO_DATE('08-10-2016','dd-mm-yyyy'),1,1);
INSERT INTO VENTA VALUES(7,0,0,0,TO_DATE('04-09-2016','dd-mm-yyyy'),7,4);
INSERT INTO VENTA VALUES(8,0,0,0,TO_DATE('05-04-2016','dd-mm-yyyy'),7,1);
INSERT INTO VENTA VALUES(9,0,0,0,TO_DATE('10-06-2016','dd-mm-yyyy'),9,1);
INSERT INTO VENTA VALUES(10,0,0,0,TO_DATE('11-02-2016','dd-mm-yyyy'),9,2);
INSERT INTO VENTA VALUES(11,0,0,0,TO_DATE('10-12-2016','dd-mm-yyyy'),7,6);
INSERT INTO VENTA VALUES(12,0,0,0,TO_DATE('03-10-2016','dd-mm-yyyy'),1,1);
INSERT INTO VENTA VALUES(13,0,0,0,TO_DATE('04-04-2016','dd-mm-yyyy'),8,2);
INSERT INTO VENTA VALUES(14,0,0,0,TO_DATE('06-06-2016','dd-mm-yyyy'),6,7);
INSERT INTO VENTA VALUES(15,0,0,0,TO_DATE('08-04-2016','dd-mm-yyyy'),1,7);
INSERT INTO VENTA VALUES(16,0,0,0,TO_DATE('08-11-2016','dd-mm-yyyy'),1,11);
INSERT INTO VENTA VALUES(17,0,0,0,TO_DATE('10-12-2016','dd-mm-yyyy'),3,11);
INSERT INTO VENTA VALUES(18,0,0,0,TO_DATE('08-03-2016','dd-mm-yyyy'),3,10);
INSERT INTO VENTA VALUES(19,0,0,0,TO_DATE('10-12-2016','dd-mm-yyyy'),3,9);

-- VENTA 1
INSERT INTO TICKET VALUES(1,20,'A',0,1,1);
INSERT INTO TICKET VALUES(2,21,'A',0,1,1);
INSERT INTO TICKET VALUES(3,22,'A',0,1,1);
INSERT INTO DETALLE VALUES(1,1,'S');
INSERT INTO DETALLE VALUES(2,1,'S');
INSERT INTO DETALLE VALUES(3,1,'S');
-- VENTA 2
INSERT INTO TICKET VALUES(4,45,'J',0,1,2);
INSERT INTO TICKET VALUES(5,46,'J',0,1,2);
INSERT INTO DETALLE VALUES(4,2,'S');
INSERT INTO DETALLE VALUES(5,2,'S');
-- VENTA 3
INSERT INTO TICKET VALUES(6,10,'A',0,2,1);
INSERT INTO TICKET VALUES(7,11,'A',0,2,1);
INSERT INTO TICKET VALUES(8,12,'A',0,2,1);
INSERT INTO DETALLE VALUES(6,3,'S');
INSERT INTO DETALLE VALUES(7,3,'S');
INSERT INTO DETALLE VALUES(8,3,'N');
-- VENTA 4
INSERT INTO TICKET VALUES(9,30,'H',0,3,4);
INSERT INTO TICKET VALUES(10,31,'H',0,3,4);
INSERT INTO TICKET VALUES(11,32,'H',0,3,4);
INSERT INTO TICKET VALUES(12,33,'H',0,3,4);
INSERT INTO TICKET VALUES(13,34,'H',0,3,4);
INSERT INTO DETALLE VALUES(9,4,'S');
INSERT INTO DETALLE VALUES(10,4,'S');
INSERT INTO DETALLE VALUES(11,4,'S');
INSERT INTO DETALLE VALUES(12,4,'N');
INSERT INTO DETALLE VALUES(13,4,'N');
-- VENTA 5
INSERT INTO TICKET VALUES(14,20,'A',0,1,1);
INSERT INTO DETALLE VALUES(14,5,'S');
-- VENTA 6
INSERT INTO TICKET VALUES(15,50,'A',0,1,3);
INSERT INTO TICKET VALUES(16,51,'A',0,1,3);
INSERT INTO TICKET VALUES(17,20,'A',0,1,3);
INSERT INTO DETALLE VALUES(15,6,'S');
INSERT INTO DETALLE VALUES(16,6,'S');
INSERT INTO DETALLE VALUES(17,6,'S');
-- VENTA 7
INSERT INTO TICKET VALUES(18,20,'B',0,4,1);
INSERT INTO DETALLE VALUES(18,7,'S');
-- VENTA 8
INSERT INTO TICKET VALUES(19,10,'A',0,4,3);
INSERT INTO TICKET VALUES(20,11,'A',0,4,3);
INSERT INTO TICKET VALUES(21,16,'A',0,4,3);
INSERT INTO DETALLE VALUES(19,8,'S');
INSERT INTO DETALLE VALUES(20,8,'S');
INSERT INTO DETALLE VALUES(21,8,'S');
-- VENTA 9
INSERT INTO TICKET VALUES(22,60,'N',0,3,1);
INSERT INTO DETALLE VALUES(22,9,'S');
-- VENTA 10
INSERT INTO TICKET VALUES(23,1,'A',0,4,1);
INSERT INTO TICKET VALUES(24,2,'A',0,4,1);
INSERT INTO TICKET VALUES(25,3,'A',0,4,1);
INSERT INTO DETALLE VALUES(23,10,'S');
INSERT INTO DETALLE VALUES(24,10,'N');
INSERT INTO DETALLE VALUES(25,10,'S');
-- VENTA 11
INSERT INTO TICKET VALUES(26,34,'B',0,2,6);
INSERT INTO TICKET VALUES(27,23,'A',0,2,6);
INSERT INTO TICKET VALUES(28,24,'A',0,2,6);
INSERT INTO DETALLE VALUES(26,11,'S');
INSERT INTO DETALLE VALUES(27,11,'S');
INSERT INTO DETALLE VALUES(28,11,'N');
-- VENTA 12
INSERT INTO TICKET VALUES(29,33,'C',0,4,1);
INSERT INTO DETALLE VALUES(29,12,'S');
-- VENTA 13
INSERT INTO TICKET VALUES(30,10,'A',0,4,1);
INSERT INTO DETALLE VALUES(30,13,'S');
-- VENTA 14
INSERT INTO TICKET VALUES(31,60,'T',0,3,1);
INSERT INTO TICKET VALUES(32,61,'T',0,3,1);
INSERT INTO TICKET VALUES(33,62,'T',0,3,1);
INSERT INTO DETALLE VALUES(31,14,'S');
INSERT INTO DETALLE VALUES(32,14,'N');
INSERT INTO DETALLE VALUES(33,14,'S');
-- VENTA 15
INSERT INTO TICKET VALUES(34,20,'A',0,1,1);
INSERT INTO TICKET VALUES(35,20,'A',0,1,1);
INSERT INTO DETALLE VALUES(34,15,'S');
INSERT INTO DETALLE VALUES(35,15,'S');
-- VENTA 16
INSERT INTO TICKET VALUES(36,32,'C',0,4,2);
INSERT INTO TICKET VALUES(37,33,'C',0,4,2);
INSERT INTO DETALLE VALUES(36,16,'S');
INSERT INTO DETALLE VALUES(37,16,'S');
-- VENTA 17
INSERT INTO TICKET VALUES(38,22,'A',0,6,1);
INSERT INTO DETALLE VALUES(38,17,'S');
-- VENTA 18
INSERT INTO TICKET VALUES(39,20,'B',0,6,1);
INSERT INTO TICKET VALUES(40,21,'B',0,6,1);
INSERT INTO TICKET VALUES(41,22,'B',0,6,1);
INSERT INTO DETALLE VALUES(39,18,'N');
INSERT INTO DETALLE VALUES(40,18,'S');
INSERT INTO DETALLE VALUES(41,18,'S');
-- VENTA 19
INSERT INTO TICKET VALUES(42,10,'A',0,5,4);
INSERT INTO TICKET VALUES(43,11,'A',0,5,4);
INSERT INTO DETALLE VALUES(42,19,'S');
INSERT INTO DETALLE VALUES(43,19,'S');

INSERT INTO DESCUENTOENTRADAS VALUES(1,0.01,1000,2000);
INSERT INTO DESCUENTOENTRADAS VALUES(2,0.02,2001,3000);
INSERT INTO DESCUENTOENTRADAS VALUES(3,0.04,3001,5000);


CREATE TABLE RESUMEN_PELICULAS(
  ID NUMBER,
  PELICULA VARCHAR2(50),
  IDIOMA VARCHAR2(45),
  CATEGORIA VARCHAR2(45),
  ENTRADAS_ADULTO NUMBER,
  ENTRADAS_NINO NUMBER,
  RECAUDACION NUMBER
);


CREATE TABLE RESUMEN_CINE(
  ID NUMBER PRIMARY KEY,
  FECHA DATE,
  CINE VARCHAR2(45),
  PELICULA VARCHAR2(45),
  IDIOMA VARCHAR2(45),
  ENTRADAS NUMBER,
  RECAUDACION NUMBER
);
CREATE SEQUENCE SQ_NUM;
CREATE SEQUENCE SQ_RP;
CREATE SEQUENCE SQ_ERROR;

commit;