CREATE USER prueba_2 IDENTIFIED BY prueba_2
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER prueba_2 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO prueba_2;
GRANT "RESOURCE" TO prueba_2;
ALTER USER prueba_2 DEFAULT ROLE "RESOURCE";


alter session set "_oracle_script"=true;